name: webspark_test_task
description: "An incredibly interesting test task that I gave my all to"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
